Nylle/JavaFixture

- src/main/java/com/github/nylle/javafixture/ReflectionHelper.java
- src/main/java/com/github/nylle/javafixture/SpecimenFactory.java
- src/main/java/com/github/nylle/javafixture/specimen/TemporalSpecimen.java
- src/main/java/com/github/nylle/javafixture/specimen/TimeSpecimen.java
- src/test/java/com/github/nylle/javafixture/ReflectionHelperTest.java
- src/test/java/com/github/nylle/javafixture/SpecimenFactoryTest.java
- src/test/java/com/github/nylle/javafixture/specimen/TemporalSpecimenTest.java
- src/test/java/com/github/nylle/javafixture/specimen/TimeSpecimenTest.java
That should cover most of the cases where JavaFIxture is used.
There are still some exotic classes like java.time.chrono.Era which need to be covered
> JAVAFIXTURE-6 Add Specimen for Temporal interface and java.time.package

- src/main/java/com/github/nylle/javafixture/ProxyFactory.java
- src/main/java/com/github/nylle/javafixture/SpecimenFactory.java
- src/main/java/com/github/nylle/javafixture/extension/JavaFixtureExtension.java
- src/main/java/com/github/nylle/javafixture/extension/JavaFixtureProvider.java
- src/main/java/com/github/nylle/javafixture/specimen/GenericSpecimen.java
- src/main/java/com/github/nylle/javafixture/specimen/InterfaceSpecimen.java
- src/test/java/com/github/nylle/javafixture/JavaFixtureTest.java
- src/test/java/com/github/nylle/javafixture/extension/JavaFixtureClassExtensionTest.java
- src/test/java/com/github/nylle/javafixture/extension/TestWithFixtureTest.java
- src/test/java/com/github/nylle/javafixture/testobjects/ITestGeneric.java
- src/test/java/com/github/nylle/javafixture/testobjects/ITestGenericInside.java
- src/test/java/com/github/nylle/javafixture/testobjects/TestObjectWithNestedGenericInterfaces.java
While adding support for generics, the interfaces have been forgotten.
Now, generic interfaces like IPair<K, V> can be proxied.
> JAVAFIXTURE-25: Add support for generic interfaces

- src/main/java/com/github/nylle/javafixture/Configuration.java
- src/main/java/com/github/nylle/javafixture/Fixture.java
- src/main/java/com/github/nylle/javafixture/PseudoRandom.java
- src/main/java/com/github/nylle/javafixture/SpecimenFactory.java
- src/main/java/com/github/nylle/javafixture/specimen/PrimitiveSpecimen.java
- src/test/java/com/github/nylle/javafixture/PseudoRandomTest.java
- src/test/java/com/github/nylle/javafixture/specimen/PrimitiveSpecimenTest.java
When numbers (short, int, long, float, double) are generated, they contain any value between the maximum negative and maximum positive value for the type. This behaviour is generally favourable. However, there might be cases in which a negative value might not make much sense, e.g. for file size or length of things.
> JAVAFIXTURE-26: Allow configuration setting for numbers to be positive-only 

- README.md
- src/main/java/com/github/nylle/javafixture/CustomizationContext.java
- src/main/java/com/github/nylle/javafixture/Fixture.java
- src/main/java/com/github/nylle/javafixture/InstanceFactory.java
- src/main/java/com/github/nylle/javafixture/ProxyInvocationHandler.java
- src/main/java/com/github/nylle/javafixture/SpecimenBuilder.java
- src/main/java/com/github/nylle/javafixture/SpecimenType.java
- src/main/java/com/github/nylle/javafixture/specimen/GenericSpecimen.java
- src/main/java/com/github/nylle/javafixture/specimen/InterfaceSpecimen.java
- src/main/java/com/github/nylle/javafixture/specimen/ObjectSpecimen.java
- src/test/java/com/github/nylle/javafixture/FixtureTest.java
- src/test/java/com/github/nylle/javafixture/InstanceFactoryTest.java
- src/test/java/com/github/nylle/javafixture/testobjects/TestObjectWithGenericConstructor.java
- src/test/java/com/github/nylle/javafixture/testobjects/TestObjectWithPrivateConstructor.java
- src/test/java/com/github/nylle/javafixture/testobjects/TestObjectWithoutDefaultConstructor.java
This will alow the user to create a new instance by using a random constructor, if one is available. If not, the object will be created "empty" meaning the fields will not be filled and thus be either null
or default-value.
It is important to keep in mind, that objects created this way cannot be customized any further.
> JAVAFIXTURE-12: Allow Use of Random Constructor

- src/main/java/com/github/nylle/javafixture/annotations/testcases/ReflectedTestCase.java
- src/test/java/com/github/nylle/javafixture/annotations/testcases/TestCaseTest.java
This avoids an exception, when a wrapper class (eg. Integer) is used as a test method argument, that corresponds to a primitive parameter in the @TestCase annotation.
Some insight provided by the [Apache Commons Lang](https://commons.apache.org/proper/commons-lang/) library, specifically:
https://commons.apache.org/proper/commons-lang/apidocs/src-html/org/apache/commons/lang3/ClassUtils.html#line.866
> Fix an exception when using primitive wrappers in test method arguments

- src/main/java/com/github/nylle/javafixture/Configuration.java
- src/main/java/com/github/nylle/javafixture/Fixture.java
- src/test/java/com/github/nylle/javafixture/ConfigurationTest.java
- src/test/java/com/github/nylle/javafixture/FixtureTest.java
The static method `configuration()` on the `Fixture`-class now returns a default-`Configuration`. 
Additionally the `Configuration`-class now can create a new `Fixture` with itself as argument.
> JAVAFIXTURE-41: Add support for fluent configuration

- src/main/java/com/github/nylle/javafixture/Fixture.java
- src/main/java/com/github/nylle/javafixture/ISpecimenBuilder.java
- src/main/java/com/github/nylle/javafixture/SpecimenBuilder.java
- src/test/java/com/github/nylle/javafixture/FixtureTest.java
This allows the creation of an Optional<T> for the desired type T.
> JF-54: Add syntactic sugar for Optional

- .editorconfig
- src/main/java/com/github/nylle/javafixture/SpecimenFactory.java
- src/main/java/com/github/nylle/javafixture/SpecimenType.java
- src/main/java/com/github/nylle/javafixture/specimen/SpecialSpecimen.java
- src/test/java/com/github/nylle/javafixture/SpecimenFactoryTest.java
- src/test/java/com/github/nylle/javafixture/SpecimenTypeTest.java
- src/test/java/com/github/nylle/javafixture/specimen/SpecialSpecimenTest.java
Files and URIs cannot be constructed with any argument and therefore need "special" treatment.
We need selected constructors to build valid objects.
Using selected constructors for these makes this code work with a JDK 17 environment (even if the code is compiled with JDK 11)
This is a preparation step for JF-63
> add SpecialSpecimen to fixture File and URI

- pom.xml
- src/main/java/com/github/nylle/javafixture/annotations/fixture/TestWithFixture.java
- src/main/java/com/github/nylle/javafixture/specimen/PrimitiveSpecimen.java
- src/test/java/com/github/nylle/javafixture/FixtureWithValidationTest.java
- src/test/java/com/github/nylle/javafixture/testobjects/TestObjectWithJavaxValidationAnnotations.java
I quickly (and dirtily) added support for the `@Column`-annotation (only the `length`-property of course).
@akutschera, would you mind having a look and maybe give me your opinion? I'm not quite sure if it is a good idea to introduce yet another dependency (`jakarta.persistence`) or would it be better to have both annotations on the entity like so:
```java
@Column(length = 5)
@Size(max = 5)
private String myLimitedString;
```
Further reading: [Baeldung](https://www.baeldung.com/jpa-size-length-column-differences)
What do you think?
> #61 Column validation annotation

- src/main/java/com/github/nylle/javafixture/InstanceFactory.java
- src/test/java/com/github/nylle/javafixture/InstanceFactoryTest.java
- src/test/java/com/github/nylle/javafixture/testobjects/factorymethod/FactoryMethodWithArgument.java
- src/test/java/com/github/nylle/javafixture/testobjects/factorymethod/FactoryMethodWithGenericArgument.java
- src/test/java/com/github/nylle/javafixture/testobjects/factorymethod/FactoryMethodWithoutArgument.java
- src/test/java/com/github/nylle/javafixture/testobjects/factorymethod/TestObjectWithNonPublicFactoryMethods.java
method.invoke needs an object that this method is invoked on, even if the method is static (in which case the object may be null).
Generic parameters are a different type than non-generic parameters, therefore we need to get the invocation parameter types from a different source. Not pretty, but it seems to work.
Refs: JF-67
> fix: use parameter types when present

- src/main/java/com/github/nylle/javafixture/Context.java
- src/main/java/com/github/nylle/javafixture/InstanceFactory.java
- src/main/java/com/github/nylle/javafixture/specimen/GenericSpecimen.java
- src/main/java/com/github/nylle/javafixture/specimen/ObjectSpecimen.java
- src/test/java/com/github/nylle/javafixture/ContextTest.java
- src/test/java/com/github/nylle/javafixture/FixtureTest.java
- src/test/java/com/github/nylle/javafixture/InstanceFactoryTest.java
- src/test/java/com/github/nylle/javafixture/annotations/fixture/JavaFixtureClassExtensionTest.java
- src/test/java/com/github/nylle/javafixture/annotations/fixture/TestWithFixtureTest.java
- src/test/java/com/github/nylle/javafixture/specimen/GenericSpecimenTest.java
- src/test/java/com/github/nylle/javafixture/specimen/ObjectSpecimenTest.java
- src/test/java/com/github/nylle/javafixture/testobjects/factorymethod/ConstructorExceptionAndFactoryMethod.java
- src/test/java/com/github/nylle/javafixture/testobjects/factorymethod/FactoryMethodWithGenericArgument.java
- src/test/java/com/github/nylle/javafixture/testobjects/factorymethod/GenericClassWithFactoryMethodWithoutArgument.java
This should solve JF-63
Because we now generate a random Optional, an empty optional is possible. Therefore I removed all the assertions that check for a valid optional value (it should be enough to check that an Optional was created), we have enough other checks that ensure a generic value has the right type.
> Jf 63 constructor fallback to factory

- src/test/java/com/github/nylle/javafixture/FixtureTest.java
In JDK 11 this throws a StackOverflowError
which is not an exception so we don't catch it.
I did not catch it because I used JDK 17 to develop this.
> test: Disable create(Throwable) test

- pom.xml
- src/main/java/com/github/nylle/javafixture/Reflector.java
- src/main/java/com/github/nylle/javafixture/specimen/GenericSpecimen.java
- src/main/java/com/github/nylle/javafixture/specimen/ObjectSpecimen.java
- src/test/java/com/github/nylle/javafixture/InstanceFactoryTest.java
- src/test/java/com/github/nylle/javafixture/ReflectorTest.java
A little refactoring. I think it's better to catch all Reflection-related exceptions in the Reflector class.
This way it's easier to just catch a SpecimenException and not worry about what else we might see in the *Specimen classes.
As a bonus this will allow us to already create a Java 17 record.
> Catch reflection exceptions

- src/main/java/com/github/nylle/javafixture/specimen/GenericSpecimen.java
- src/main/java/com/github/nylle/javafixture/specimen/ObjectSpecimen.java
- src/test/java/com/github/nylle/javafixture/specimen/GenericSpecimenTest.java
- src/test/java/com/github/nylle/javafixture/specimen/ObjectSpecimenTest.java
Refs: JF-75
Anything that is customized in 
```
fixture().build(MyClass.class).with("field", "value")
```
will only be applied to MyClass. It is not (yet) possible to customize fields in fields of MyClass. For that you would have to create a fixture of the field object and set it in MyClass.
> fix: use customization in top-level object only

- src/main/java/com/github/nylle/javafixture/SpecimenType.java
- src/main/java/com/github/nylle/javafixture/specimen/SpecialSpecimen.java
- src/test/java/com/github/nylle/javafixture/SpecimenTypeTest.java
- src/test/java/com/github/nylle/javafixture/specimen/SpecialSpecimenTest.java
By limiting the number of bits to max. 1024, we save some time.
Creating a BigInteger with Integer.MAX_VALUE bits can easily take
one second or more.
Refs: JF-78
> feat: add BigInteger to SpecialSpecimen

- src/main/java/com/github/nylle/javafixture/specimen/PrimitiveSpecimen.java
The switch with String cases allows us to only
use the classes that have already been loaded because we are parsing an annotation that has already been used.
Refs: #82
> fix: load annotation class on demand

- src/main/java/com/github/nylle/javafixture/InstanceFactory.java
- src/test/java/com/github/nylle/javafixture/InstanceFactoryTest.java
- src/test/java/com/github/nylle/javafixture/testobjects/withconstructor/TestObjectWithConstructedField.java
Only the top-level object's fields can be customized. By removing the field from the customization context, we ensure it is not used again.
Refs: #92
> Use customized fields only once.

- src/main/java/com/github/nylle/javafixture/SpecimenFactory.java
- src/main/java/com/github/nylle/javafixture/specimen/EnumSpecimen.java
- src/main/java/com/github/nylle/javafixture/specimen/PredefinedSpecimen.java
- src/main/java/com/github/nylle/javafixture/specimen/PrimitiveSpecimen.java
- src/main/java/com/github/nylle/javafixture/specimen/TimeSpecimen.java
- src/test/java/com/github/nylle/javafixture/FixtureTest.java
- src/test/java/com/github/nylle/javafixture/SpecimenFactoryTest.java
- src/test/java/com/github/nylle/javafixture/specimen/EnumSpecimenTest.java
- src/test/java/com/github/nylle/javafixture/specimen/PredefinedSpecimenTest.java
- src/test/java/com/github/nylle/javafixture/specimen/PrimitiveSpecimenTest.java
- src/test/java/com/github/nylle/javafixture/specimen/TimeSpecimenTest.java
During the fix I noticed that we can simplify the caching by checking for chached values in the SpecimenFactory instead of each Specimen.
A bonus effect is that we don't construct e.g. PrimitiveSpecimen anymore that we won't use because the type was pre-defined.
> Issue 98 - use pre-defined instances when creating fixtures

- pom.xml
AssertJ 3.25.1 has a byte-buddy version that can handle Java 21 class files.
The update to Mockito 5.11 allows us to get rid of the mockito-inline dependency.
This only affects testing of JavaFixture.
The resulting code is still compatible with Java 11.
It's just convenience when you try to run the JavaFixture tests locally and your default Java version is > 19.
> make code compilable with OpenJDK21

- src/main/java/com/github/nylle/javafixture/InstanceFactory.java
- src/main/java/com/github/nylle/javafixture/specimen/AbstractSpecimen.java
- src/test/java/com/github/nylle/javafixture/InstanceFactoryTest.java
- src/test/java/com/github/nylle/javafixture/specimen/AbstractSpecimenTest.java
- src/test/java/com/github/nylle/javafixture/specimen/GenericSpecimenTest.java
- src/test/java/com/github/nylle/javafixture/testobjects/abstractclasses/AbstractClassWithConstructorException.java
- src/test/java/com/github/nylle/javafixture/testobjects/withconstructor/ConstructorExceptionAndNoFactoryMethod.java
- src/test/java/com/github/nylle/javafixture/testobjects/withconstructor/ConstructorExceptionAndThrowingFactoryMethod.java
> Pass exceptions on to manufacture method

- pom.xml
Just a few dependency upgrades.
I checked and could run all tests with JDKs 11, 17, 21, 22, 23 and 24.
This will only affect working on the code with a local JDK version of 24.
The resulting byte code version is still 11.
> build: upgrade dependencies for Java 24 #117
